### ISSUE TITLE
Detailed view

### ISSUE THREAD

**Issue by tomasz-oponowicz** [tomasz-oponowicz/markets#26]
Symbols have a lot of information to show.

In order to provide useful information and keep the user interface clean, we would like to introduce a new detailed view. A user could access it by clicking a symbol in the list view. Additionally the list view could be simplified by moving extra data to the detailed view.

## List view

For each symbol:
* Symbol ID
* Symbol human readable name
* Price
* Price change
* Pre/Post Market price change

## Detailed view

* Symbol ID
* Symbol human readable name
* Is market open/closed?
* Last update time
* Currency
* Price
* Price change
* Price change percent
* Pre/Post Market price
* Pre/Post Market price change
* Pre/Post Market price change percent
* Price chart, modes:
  - 1 day
  - 5 days
  - 1 month
  - 1 year
  - 5 years
* Actions:
  - Copy Price
  - Open Yahoo Finance for details

_Note:_ Stocks have concept of [the after hours trading](https://www.investopedia.com/ask/answers/after-hours-trading-am-i-able-to-trade-at-this-time/) (_Pre/Post Market *_ values). Other instruments, like currencies or cryptocurrencies, don't have this concept.

## Inspiration

Various screenshots of Yahoo Finance and MSN Money apps:

![ms1](https://user-images.githubusercontent.com/615940/90609849-ee101780-e204-11ea-9e73-fe060c241a78.jpg)
![ms2](https://user-images.githubusercontent.com/615940/90610187-5f4fca80-e205-11ea-9475-595149ae527c.jpg)
![yahoo1](https://user-images.githubusercontent.com/615940/90610191-5fe86100-e205-11ea-9904-5114c3edff40.jpg)
![yahoo2](https://user-images.githubusercontent.com/615940/90610192-6080f780-e205-11ea-9f13-ac64ec65cb53.jpg)
![yahoo3](https://user-images.githubusercontent.com/615940/90610195-61198e00-e205-11ea-803f-93dd4771b02d.jpg)
![yahoo4](https://user-images.githubusercontent.com/615940/90610197-61b22480-e205-11ea-96af-a52d563f314f.jpg)

**Comment by bertob** [comment]
I know nothing about stocks, but in terms of visuals/structure I think the second example you have here feels a lot better. I think that layout would map fairly well to the GNOME HIG, with the exception of the Summary/Details tabs, I think it'd be better to put details in a sub-view or just below the other content on the summary view.

**Comment by tomasz-oponowicz** [comment]
hey Tobias, thank you for your feedback.

I agree that the second view feels more natural in the Gnome environment.

With regard to tabs, I think they are not needed. According to listed properties, the summary view should be enough.

**Comment by casasfernando** [comment]
I installed this app using flatpak in Elementary OS and it is very promising.
It looks really good and adding a detailed view in the app would be great since I don't like being taken to Yahoo website for the details.

Keep up with great work @tomasz-oponowicz
